version: '3.1'

services:

# PHP/Apache with mysql-client
  app:
    container_name: obtain_it_app
    image: codepulse/php-7.2.0-apache-mysql
    volumes:
      - .:/var/www:cached
      - ./Docker/etc/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf:cached

    working_dir: /var/www/docroot
    depends_on:
      - db
    ports:
      - "8001:80"
    links:
      - db
    restart: always

# Database service
  db:
    image: percona:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3309:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal_db_obtainit
      MYSQL_USER: root
      MYSQL_PASSWORD: password

# Volumes to make sure I do not lose any data
volumes:
  db_data: