<?php

/**
 * Implement hook_theme().
 */
function obtainit_styleguide_theme($existing, $type, $theme, $path) {
  return array(
    'style_guide' => array(
      'variables' => array(
        'TEMPLATE_DIR' => NULL,
      ),
    ),
    'item_page' => array(
      'variables' => array(
        'TEMPLATE_DIR' => NULL,
      ),
    ),
    'listing_page' => array(
      'variables' => array(
        'TEMPLATE_DIR' => NULL,
      ),
    ),
    'login_page' => array(
      'variables' => array(
        'TEMPLATE_DIR' => NULL,
      ),
    ),
  );
}
